name: Docker CI

on:
  push:
    branches: [ fix_Dockerfile ]

jobs:
  install_kbsdk_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout git repo
      uses: actions/checkout@v2

    - name: Add bin to $PATH
      run: |
        echo "::add-path::$GITHUB_WORKSPACE/bin"

    - name: We're on GitHub!
      shell: bash
      run: |
        touch running_on_github.txt

    - name: pull and run docker image
      shell: bash
      env:
        KBASE_TEST_TOKEN: ${{ secrets.KBASE_TEST_TOKEN }}
      run: |
        docker pull ialarmedalien/kb-sdk
        mkdir -p bin
        docker run ialarmedalien/kb-sdk genscript > bin/kb-sdk
        chmod 755 bin/kb-sdk
        kb-sdk test

  # push_to_dockerhub:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Build & Push to Docker Hub
  #       uses: opspresso/action-docker@master
  #       with:
  #         args: --docker
  #       env:
  #         USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #         PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  #         IMAGE_NAME: "ialarmedalien/kbase_checkm_base"
  #         DOCKERFILE: "Dockerfile_checkM"
  #         TAG_NAME: "fix_Dockerfile"
  #         LATEST: "true"
